name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  push-backend:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout backend
        uses: actions/checkout@v3
        with:
          path: backend

      - name: Config git credentials
        run: |
          git config --global user.name ${{ secrets.PERSONAL_USERNAME }}
          git config --global user.email ${{ secrets.PERSONAL_EMAIL }}

      - name: Push Backend
        run: |
          rm -rf .git || true
          git clone https://${{ secrets.PERSONAL_USERNAME }}:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ secrets.PERSONAL_USERNAME }}/${{ secrets.PERSONAL_BACKEND_REPO }}.git
          cp -rT backend ${{ secrets.PERSONAL_BACKEND_REPO }}/
          cd ${{ secrets.PERSONAL_BACKEND_REPO }}
          git add --all
          git commit -m "Update backend folder"
          git push -u origin main