---
name: Github Repo Generator 🐙
'on':
  workflow_dispatch:
    inputs:
      repo_name:
        description: Name of the repository
      repo_visibility:
        description: Visibility of the repository
        type: choice
        default: public
        options:
          - private
          - public
      repo_description:
        description: Description of the repository
        default: Projectopia is a project management tool for software development teams.
      backend_dir:
        description: Directory for the backend
        default: server
      frontend_dir:
        description: Directory for the frontend
        default: client
      github_token:
        description: GitHub Personal Access Token
        required: true
      github_owner:
        description: GitHub Username/Organization
        required: true
jobs:
  terraform:
    name: Terraform
    uses: ./.github/workflows/terraform.yaml
    with:
      repo_name: ${{ github.event.inputs.repo_name }}
      repo_visibility: ${{ github.event.inputs.repo_visibility }}
      repo_description: ${{ github.event.inputs.repo_description }}
      backend_dir: ${{ github.event.inputs.backend_dir }}
      frontend_dir: ${{ github.event.inputs.frontend_dir }}
      github_token: ${{ github.event.inputs.github_token }}
      github_owner: ${{ github.event.inputs.github_owner }}