---
name: Linter ⏹️
'on':
  workflow_call:
    inputs:
      github_token:
        type: string
        description: GitHub Token
        required: true
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JSCPD: false
          VALIDATE_YAML: true
          VALIDATE_XML: true
          GITHUB_TOKEN: ${{ github.event.inputs.github_token }}