---
  name: Unit Tests
  'on':
    workflow_call:
      inputs:
        github_token:
          description: GitHub Token
          required: true
          type: string
  jobs:
    unit:
      name: Unit Tests
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Unit Tests
          run: |
            echo "Unit Tests, will be added later"